version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: hillliu/django-slim
    docker:
      - image: circleci/buildpack-deps:18.04

jobs:
  build-and-publish:
    parameters:
      docker-tag:
        type: string
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Log time
          command: date
      - run:
          name: Gen Docker file
          command: |
            ./build.sh << parameters.docker-tag >>
            ls -la ver-<< parameters.docker-tag >>
      - run:
          name: Build Docker image
          command: |
            docker build -f ver-<< parameters.docker-tag >>/Dockerfile \
              -t $IMAGE_NAME:<< parameters.docker-tag >> \
              ./ver-<< parameters.docker-tag >>
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            ./compile.sh p << parameters.docker-tag >>
      - run:
          name: Build app
          command: |
            docker build -f ver-<< parameters.docker-tag >>/Dockerfile.app \
              -t $IMAGE_NAME:app-<< parameters.docker-tag >> \
              ./ver-<< parameters.docker-tag >>
      - run:
          name: Publish app
          command: |
            sourceImage=$IMAGE_NAME:app-<< parameters.docker-tag >> \
            DOCKER_FILE=Dockerfile.app \
            ./compile.sh p << parameters.docker-tag >> app

workflows:
  run-job:
    jobs:
      - build-and-publish:
          matrix:
            parameters:
              docker-tag: ["3.8"]
